dist: xenial
language: python
cache: pip
services:
  - postgresql
  - mysql
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
env:
  global:
    - IMPORT_EXPORT_POSTGRESQL_USER=postgres
    - IMPORT_EXPORT_POSTGRESQL_PASSWORD=
    - IMPORT_EXPORT_MYSQL_USER=root
    - IMPORT_EXPORT_MYSQL_PASSWORD=
  matrix:
    - DJANGO="Django>=2.0,<2.1" IMPORT_EXPORT_TEST_TYPE=postgres
    - DJANGO="Django>=2.0,<2.1" IMPORT_EXPORT_TEST_TYPE=mysql-innodb
    - DJANGO="Django>=2.0,<2.1" IMPORT_EXPORT_TEST_TYPE=sqlite
    - DJANGO="Django>=2.1,<2.2" IMPORT_EXPORT_TEST_TYPE=postgres
    - DJANGO="Django>=2.1,<2.2" IMPORT_EXPORT_TEST_TYPE=mysql-innodb
    - DJANGO="Django>=2.1,<2.2" IMPORT_EXPORT_TEST_TYPE=sqlite
    - DJANGO="https://github.com/django/django/archive/master.tar.gz" IMPORT_EXPORT_TEST_TYPE=postgres
    - DJANGO="https://github.com/django/django/archive/master.tar.gz" IMPORT_EXPORT_TEST_TYPE=mysql-innodb
    - DJANGO="https://github.com/django/django/archive/master.tar.gz" IMPORT_EXPORT_TEST_TYPE=sqlite
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz" IMPORT_EXPORT_TEST_TYPE=postgres
    - python: "3.5"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz" IMPORT_EXPORT_TEST_TYPE=sqlite
    - python: "3.5"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz" IMPORT_EXPORT_TEST_TYPE=mysql-innodb
install:
  - pip install -q $DJANGO
  - pip install tablib==0.12.1
  - pip install -r requirements/base.txt
  - pip install -r requirements/test.txt
  - pip install coveralls
script:
   - python -Wall -m coverage run --omit='setup.py' --source=. tests/manage.py test core --settings=
   - isort --check-only
after_success:
  - coveralls

