language: python
cache: pip
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"
  - DJANGO="Django>=1.11,<1.12"
  - DJANGO="Django>=2.0,<2.1"
  - DJANGO="Django>=2.1,<2.2"
  - DJANGO="https://github.com/django/django/archive/master.tar.gz"
install:
  - pip install -q $DJANGO
  - pip install tablib==0.12.1
  - pip install -r requirements/base.txt
  - pip install coveralls
script:
   - python -Wall `which coverage` run --omit='setup.py' --source=. tests/manage.py test core --settings=
after_success:
  - coveralls
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="Django>=1.9,<1.10"
    - python: "3.3"
      env: DJANGO="Django>=1.10,<1.11"
    - python: "2.7"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
    - python: "2.7"
      env: DJANGO="Django>=2.0,<2.1"
    - python: "2.7"
      env: DJANGO="Django>=2.1,<2.2"
    - python: "3.3"
      env: DJANGO="Django>=1.11,<1.12"
    - python: "3.3"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
    - python: "3.3"
      env: DJANGO="Django>=2.0,<2.1"
    - python: "3.3"
      env: DJANGO="Django>=2.1,<2.2"
    - python: "3.4"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
    - python: "3.4"
      env: DJANGO="Django>=2.1,<2.2"
    - python: "3.6"
      env: DJANGO="Django>=1.8,<1.9"
    - python: "3.6"
      env: DJANGO="Django>=1.9,<1.10"
    - python: "3.6"
      env: DJANGO="Django>=1.10,<1.11"
  allow_failures:
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
