[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "django-import-export"
authors = [
    {name = "Bojan MihelaÄ", email = "djangoimportexport@gmail.com"},
]
maintainers = [
    {name = "Matthew Hegarty", email = "djangoimportexport@gmail.com"},
]
description = "Django application and library for importing and exporting data with included admin integration."
keywords = ["django", "import", "export"]
license = {file = "LICENSE"}
requires-python = ">=3.8"
dynamic = ["version", "readme"]
classifiers = [
    "Framework :: Django",
    "Framework :: Django :: 3.2",
    "Framework :: Django :: 4.1",
    "Framework :: Django :: 4.2",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Software Development",
]

dependencies = [
    "diff-match-patch",
    "Django>=3.2",
    "tablib[html,ods,xls,xlsx,yaml]==3.5.0",
]

[project.urls]
Documentation = "https://django-import-export.readthedocs.io/en/stable/"
Repository = "https://github.com/django-import-export/django-import-export"
Changelog = "https://github.com/django-import-export/django-import-export/blob/main/docs/changelog.rst"

[tool.setuptools]
platforms = ["OS Independent"]
license-files = ["LICENSE"]

[tool.setuptools.dynamic]
version = {attr = "import_export.__init__.__version__"}
readme = {file = ["README.rst"]}

[tool.zest-releaser]
create-wheel = true
python-file-with-version = "import_export/__init__.py"

[tool.isort]
profile = "black"

[tool.coverage.run]
parallel = true
source = "import_export"
